### ISSUE TITLE
notification didnt occured

### ISSUE THREAD

**Issue by Jeannot78140** [Der-Henning/tgtg#159]
dear Henning,

i start using your scanner, and got troubles with notifications.
i only use telegram notifications, and when a new state happens, i don't have notification.

i precise my bot seems to work, got the first notification when launching scanner.exe
![trouble notif](https://user-images.githubusercontent.com/113904306/191231895-800b0f79-c265-4ba6-8dc6-ac64e8bb1e0e.jpg)

any idea of the problem ? 

thanks a lot

**Comment by Der-Henning** [comment]
Hi @Jeannot78140.
The bot only sends notifications when the state of an item rises from 0 to something. This way you only receive a notification when bags are available that where not before.
The bot updates the state of the observed items every SLEEP_TIME seconds.

**Comment by Jeannot78140** [comment]
oh ok, didn't get that info :).

does it mean that reducting sleep_time gives a better refresh ? is there any risk to get banned by tgtg ?


you're a boss, great job.

**Comment by Der-Henning** [comment]
Yes you can reduce the sleep time. But at some point TGTG will block your requests due to a high request rate. This ban is only temporary though. Didn't hear of anybody receiving a permanent ban.
I think it is save to reduce the sleep time to 30 seconds. But you can try to reduce it further if the items in your area are sold out more quickly.

**Comment by Der-Henning** [comment]
Closing.
Feel free to reopen or create a new issue when you have any problems or bugs.
