### ISSUE TITLE
Question: Unexpected Repeat Identical Notifications (solved)

### ISSUE THREAD

**Issue by harryfear** [Der-Henning/tgtg#3]
Expected: notifications are sent when quantity available changes since last email. notifications are sent out only on numeric change to quantity available.

What happens: identical notifications can be sent in rapid succession with identical quantity available. This means repeat emails in succession alert with same quantity number

Debug print-out: {missing} (Next time this happens I will try to print/paste-out the debug information. Because I missed the last occurrence by 30 minutes to share here. And I don't see the debug info is logged to file anywhere (?).)

Affected: v1.2.1 of this repo †; also legacy ▅▅-notifications.com suffered from this issue ‡ from time to time.

***

This could be because the quantity goes up and down again to the same number between checks/notifications, but I don't think it's intended behaviour for notifications to be sent out as they are now.

Screenshots:—
•† example: https://ibb.co/3mLXYbF
•‡ example: https://ibb.co/v3y542X

**Comment by Der-Henning** [comment]
Hi @harryfear,

the scanner holds the currently available item count in the dictionary amounts. 
On each loop the new and old amount are compared. The logic is to send a notification if the amount rises from zero to something. Any other change of the available items will not trigger a notification.

> scanner.py
`if self.amounts[item.id] == 0 and item.items_available > self.amounts[item.id]: self._send_messages(item)`

The phenomenon you mention is caused by the stores that push only one bag by another after it was sold. You can see it by the delay of around 10 minutes in your example. The scanner checks by default every 20 seconds. So there is no unexpected behavior of the scanner.

Yes there are no log files at the moment. I keep this issue open for future improvements of the logging routine.

**Comment by harryfear** [comment]
That is great news and also an extremely useful feature. 

Great relief!

Thank you. 🙏🏼

**Comment by Der-Henning** [comment]
Added improved logging to main with 91dbae1baeefcaa804e60aeec0d0e3c9afee78ad
