### ISSUE TITLE
Reconnect after loss

### ISSUE THREAD

**Issue by crack00r** [Der-Henning/tgtg#321]
Sometimes the Windowsversion lose the connection and stop with red error

pls add a auto reconnect

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/230759814-b0aeca75-490d-4320-b535-9d972d7efa55.png)

**Comment by Der-Henning** [comment]
Hi @crack00r.
The errors you see are caused by connection problems to the telegram API. As you see by the timestamps, these only occur every couple of hours. This should not affect the functionality of the scanner. 
The connection problems could be caused by a bad internet connection or problems on the telegram server side.

**Comment by crack00r** [comment]
ok thx!
