### ISSUE TITLE
[Bug] Error loading Python lib '/tmp//libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp//libpython3.10.so.1.0)

### ISSUE THREAD

**Issue by KaKi87** [Der-Henning/tgtg#333]
Hello,

I'm experiencing the following error while trying to run version `1.16.2` for the first time :

```
[390722] Error loading Python lib '/tmp/_MEIg56qZq/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIg56qZq/libpython3.10.so.1.0)
```

This issue wasn't occuring on version `1.13.0`.

Thanks

**Comment by Der-Henning** [comment]
Hi @KaKi87.
On which Linux distribution/version are you running the executable? 
The executable is built on the latest Ubuntu version, which can create issues on older OS. 
I would always recommend running the scanner from source or building your own executable on Linux.

**Comment by KaKi87** [comment]
> On which Linux distribution/version are you running the executable?

Ubuntu 20.04

> The executable is built on the latest Ubuntu version, which can create issues on older OS.

I understand.
But changing compatibility is a **breaking** change, therefore it requires incrementing the **major** version number.

In which case, I would have read version `2.0.0`'s changelog beforehand.

**Comment by Der-Henning** [comment]
Yes, you are right in general. But the compatibility of the source code didn't change.
The pre-build executables are meant for none technical people so they can run the scanner on their Windows or MacOS desktop machine with minimal effort. As this is only a private side project I cannot support and test every variant of every OS. As a Linux user, I guess you could easily clone the project and run it from source :)
That's why I recommend running it with docker, where all the required libraries are bundled in the image.

**Comment by KaKi87** [comment]
Docker it is, then.
