### ISSUE TITLE
How did you find the API endpoints?

### ISSUE THREAD

**Issue by PhilippFeO** [Der-Henning/tgtg#429]
My skills in programming networking stuff are kinda limited but I am curious in finding endpoints myself! Please enlight me! :D

**Comment by itakerboust** [comment]
Sniffing the network (e.g. MITM) or reverse engineering

**Comment by Der-Henning** [comment]
Hi @PhilippFeO.
@itakerboust is right. Sniffing the network with wireshark and in this case reverse engineering the android app. You can revert the apk back to java and then try to figure out whats going on ...
But for this project the main credits go to @ahivert who published his results in https://github.com/ahivert/tgtg-python.

**Comment by Der-Henning** [comment]
@PhilippFeO you are welcome.
It is very simple. Whenever you need some software(-snippet) in most cases, someone already had the same problem.
Before implementing it yourself try to find a solution on Github. Suppose it is sufficient, use it. Otherwise, reuse what is useful and build it yourself.
In this case, if you type in "too good to go api" on Google one of the first matches is the mentioned repo.

**Comment by PhilippFeO** [comment]
Yes, my experience has already told me, that nearly all problems I encounter were solved somewhere by someone but finding it, is another story. I also slowly start digging into the open source world, ie. being provided with tips on navigating on GitHub is always welcome (fi. I didn't imagine in the first place that there are several TooGoodToGo API clients out there).
