### ISSUE TITLE
Telegram notification error : "Timed out"

### ISSUE THREAD

**Issue by JustHut** [Der-Henning/tgtg#87]
[scanner.log](https://github.com/Der-Henning/tgtg/files/8641798/scanner.log)

Hello!

I set up the scanner to receive notifications on Telegram but on the 5 times it should have sent me one because new bags were available, it only worked once. The other 4 times, an error "Timed out" occurred at the time it should send me a notification (like in the scanner.log at 17:16:42).

However there is no problem with the test notification that I received every time I launch the scanner. It also worked one other time but stopped just after, I have no idea why... By the way, I'm on MacOs. 

Do you know where the problem could be ?

Thank you!

**Comment by Der-Henning** [comment]
HI @JustHut.
Since it is a TimeOut error it probably is an issue with your connection to the telegram server. Are you directly connected to the internet or do you use some kind of proxy? 
You can try using `ping api.telegram.org` or `traceroute api.telegram.org` to get some more insights.
At the moment I cannot see any bug in my code responsible for you issue.
But we will try to work this out. Let me hear if you have some more insights.

**Comment by Der-Henning** [comment]
Hi @JustHut.
Were you able to solve the problem or is it still there?

**Comment by JustHut** [comment]
Hello!

I tried again this morning with version 10.10.1 and I still had the error 1 time out of 3 baskets. So it seems to work but it is very random.

**Comment by Der-Henning** [comment]
[1ebf3c3](https://github.com/Der-Henning/tgtg/commit/1ebf3c33182102fb675dcc34b83cdc128675e533) should solve this issue. Will be part of the next release v1.11.4.

**Comment by Der-Henning** [comment]
Closing.
If the problem persists feel free to reopen or create a new issue.
